# -*- coding: utf-8 -*-
"""DataPreprocessing_P1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NajIjbBbToeTH6JfC0gQtsMMf6uhodvE

#Import pandas library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the dataset
url = "https://archive.ics.uci.edu/static/public/942/rt-iot2022.zip"
df = pd.read_csv(url, sep=';', decimal=',')
#df.shape
# data (as pandas dataframes)
#X = df.data.features
#y = df.data.targets

# metadata
#print(df.metadata)
1
# variable information
#print(df.variables)
print (df)

df.info()

x=10
if(x>10):
  print ('x is greater than 10')
elif(x>5):
  print('x is greater than 5')
else:
  print('x is less than 5')

for x in range(0,11):
  print (x)

"""#Import the CSV file"""

df = pd.read_csv('WorldCases2023.csv')
df.shape

from google.colab import drive
drive.mount('/content/drive')

df.info()

df.columns

df.head(1)

"""# Access a single column from a Dataframe

"""

df['NewDeaths']

df.NewDeaths

df[['Country','TotalCases','NewDeaths']]

"""#Select Rows from the Dataframe"""

df.iloc[50:100,0:7]

df.iloc[0:6,0:3]

df[df['NewDeaths']== 4.0]

df[(df['Country']=='India')|(df['Country']=='USA')]

df.set_index('Country', inplace = True)
df.head(10)

"""#Set an Index of a Data Frame"""

df.head(2)

df.index

df.sort_index(ascending=False)

df.loc['France']

df.reset_index(inplace=True)

df



"""#Statistical Analysis of Dataset"""

df.describe

df['ActiveCases'].mean()

df['NewCases'].median()

"""#Cleaning Data

"""

df = pd.read_csv('WorldCases2023.csv')
df.shape
df.head(5)

df.dropna()

df.dropna(axis=0, how='any')

df.dropna(axis=0, how='all')

df.dropna(axis=0, how='any',subset=['TotalDeaths'])

df.dropna(axis=1, how='any')

df.replace('Missing',np.nan,inplace=True)

df.head()

df.fillna(0)

df.fillna(method='ffill')

df.fillna(method='bfill')

df.dtypes

df['NewRecovered'] = df['NewRecovered'].astype(float)
df['Population'] = df['Population'].str.replace(',','').astype(float)
df.interpolate()

df['NewCases'].mean()

df['NewCases'].fillna(df['NewCases'].mean())

#df = pd.read_csv('WorldCases2023.csv')
newdf = df.dropna(axis=0, how='any', subset=['Country','NewCases'] )
ct = newdf.loc[0:100, 'Country']
newCase = newdf.loc[0:100, 'NewCases']
print(ct)
print(newCase)

plt.plot(ct,newCase)

fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(ct,newCase)
ax.set_xlabel('Country')
ax.set_ylabel('New Cases')

fig, ax = plt.subplots(figsize=(10, 4))
ax.bar(ct,newCase)
ax.set_xlabel('País')
ax.set_ylabel('Casos Nuevos')